version: '3.8'

services:
  postgres:
    image: postgres
    container_name: ksbd-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ksbd
    networks:
      - ksbd

networks:
  ksbd: